### ISSUE TITLE
Unhandled exception in fetching requests job due to list index out of range in wallarm-appstructure container

### ISSUE THREAD

**Issue by chirangaalwis** [wallarm/ingress#233]
### Description

We have noticed the following application error log in `wallarm-appstructure` container of `wallarm-ingress-controller-wallarm-tarantool` Kubernetes Deployment.

```
2023-05-23 13:08:55,710 INFO     wallarm-appstructure[1] Creating the new Wallarm API client (host: us1.api.wallarm.com, port: 443, ca_verify: True, Node version: (4, 6))
2023-05-23 13:08:55,710 INFO     wallarm-appstructure[1] Wallarm API observing job started
2023-05-23 13:09:55,766 INFO     wallarm-appstructure[1] Wallarm API: Fetching client's ID...
2023-05-23 13:09:56,023 INFO     wallarm-appstructure[1] Wallarm API: Client's ID -> 11332
2023-05-23 13:09:56,126 INFO     wallarm-appstructure[1] Fetching requests job started
2023-05-23 13:09:56,126 INFO     wallarm-appstructure[1] Creating the new Wallarm API client (host: us1.api.wallarm.com, port: 443, ca_verify: True, Node version: (4, 6))
2023-05-23 13:09:56,126 INFO     wallarm-appstructure[1] Upload statistic job started
2023-05-23 13:09:56,127 INFO     wallarm-appstructure[1] AppStructure Client's activity is enabled
2023-05-23 13:09:56,168 ERROR    wallarm-appstructure[1] Unhandled exception in fetching requests job: list index out of range
Traceback (most recent call last):
  File "/opt/wallarm/python/usr/lib/python3/dist-packages/wallarm/client/fetch_requests_job.py", line 54, in run
    self.process()
  File "/opt/wallarm/python/usr/lib/python3/dist-packages/wallarm/client/fetch_requests_job.py", line 80, in process
    self.stats.add_request(request, stats_logger=self.stats_logger)
  File "/opt/wallarm/python/usr/lib/python3/dist-packages/wallarm/client/stats_storage.py", line 60, in add_request
    request, self._stats[instance], stats_logger=stats_logger
  File "/opt/wallarm/python/usr/lib/python3/dist-packages/wallarm/client/request_preprocessor.py", line 111, in call
    for entry in request.entries():
  File "/opt/wallarm/python/usr/lib/python3/dist-packages/wallarm/proton/serialized_request.py", line 264, in entries
    for entry in result.entries():
  File "/opt/wallarm/python/usr/lib/python3/dist-packages/wallarm/proton/serialized_request.py", line 78, in entries
    for e in value.entries():
  File "/opt/wallarm/python/usr/lib/python3/dist-packages/wallarm/proton/serialized_request.py", line 72, in entries
    types = cast(Dict[str, EntryParserT], self.value_types())
  File "/opt/wallarm/python/usr/lib/python3/dist-packages/wallarm/proton/serialized_request.py", line 49, in value_types
    types = self.data[1][9]
IndexError: list index out of range
2023-05-23 13:09:57,169 INFO     wallarm-appstructure[1] Fetching requests job started
2023-05-23 13:09:57,171 ERROR    wallarm-appstructure[1] Unhandled exception in fetching requests job: list index out of range
Traceback (most recent call last):
  File "/opt/wallarm/python/usr/lib/python3/dist-packages/wallarm/client/fetch_requests_job.py", line 54, in run
    self.process()
  File "/opt/wallarm/python/usr/lib/python3/dist-packages/wallarm/client/fetch_requests_job.py", line 80, in process
    self.stats.add_request(request, stats_logger=self.stats_logger)
  File "/opt/wallarm/python/usr/lib/python3/dist-packages/wallarm/client/stats_storage.py", line 60, in add_request
    request, self._stats[instance], stats_logger=stats_logger
  File "/opt/wallarm/python/usr/lib/python3/dist-packages/wallarm/client/request_preprocessor.py", line 111, in call
    for entry in request.entries():
  File "/opt/wallarm/python/usr/lib/python3/dist-packages/wallarm/proton/serialized_request.py", line 264, in entries
    for entry in result.entries():
  File "/opt/wallarm/python/usr/lib/python3/dist-packages/wallarm/proton/serialized_request.py", line 78, in entries
    for e in value.entries():
  File "/opt/wallarm/python/usr/lib/python3/dist-packages/wallarm/proton/serialized_request.py", line 72, in entries
    types = cast(Dict[str, EntryParserT], self.value_types())
  File "/opt/wallarm/python/usr/lib/python3/dist-packages/wallarm/proton/serialized_request.py", line 49, in value_types
    types = self.data[1][9]
IndexError: list index out of range
2023-05-23 13:09:58,172 INFO     wallarm-appstructure[1] Fetching requests job started
2023-05-23 13:09:58,174 ERROR    wallarm-appstructure[1] Unhandled exception in fetching requests job: list index out of range
Traceback (most recent call last):
```

No container level failures recorded.

Wallarm team, why do we experience the above?

**Comment by xDmitriev** [comment]
Please contact our support team regarding this case. Also, please provide them with more details for the ability to reproduce the issue (Kubernetes version, Helm chart version, config and etc). We can not handle such requests here since we have a standard process. Thank you for understanding.
